app/authentication/routes.py
from app.forms import UserLoginForm, UserInventoryForm, SignInForm, SignUpForm
from app.models import User, Inventory, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash

# imports for flask login 
from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = SignUpForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            first_name  = form.first_name.data
            last_name = form.last_name.data
            print(email, password)

            user = User(email, first_name, last_name, password = password)

            db.session.add(user)
            db.session.commit()

            login_user(user)

            flash(f'You have successfully created a user account {email}', 'User-created')
            return redirect(url_for('site.profile'))
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('sign_up.html', form=form, signup = True)





@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = SignInForm()
    
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successful in your initiation. Congratulations, and welcome to the Jedi Knights', 'auth-sucess')
                return redirect(url_for('site.profile'))
            else:
                flash('You have failed in your attempt to access this content', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check your Form')
    return render_template('sign_in.html', form=form, signup = False)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

@auth.route('/inventory', methods=['GET', 'POST'])
@login_required 
def inventory():
    form = UserInventoryForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            make = form.make.data
            model = form.model.data
            year = form.year.data
            color = form.color.data

            inventory_item = Inventory(make, model, year, color, user_token=current_user.token)

            db.session.add(inventory_item)
            db.session.commit()

            flash(f'You have successfully added {model} to your inventory', 'added-to-inventory')
            return redirect(url_for('auth.inventory'))
    except:
        return('Invalid form data: Please check your form')

    return render_template('inventory.html', form=form)

app/site/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash, request
from app.forms import UserInventoryForm, AddInventory, UpdateCar
from app.models import Inventory, db
from flask_login import login_required, current_user
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField

site = Blueprint('site',  __name__, template_folder='site_templates')


@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile.html')
def profile():
    return render_template('profile.html')


@site.route('/inventory', methods=['GET', 'POST'])
@login_required
def inventory():
    form = AddInventory()

    if form.validate_on_submit():
        make = form.make.data
        model = form.model.data
        year = form.year.data
        color = form.color.data

        user_token = current_user.token

        inventory_item = Inventory(make=make, model=model, year=year, color=color, user_token=user_token)

        db.session.add(inventory_item)
        db.session.commit()

        return redirect(url_for('site.inventory'))

    return render_template('inventory.html', form=form)

@site.route('/update_inventory/<id>', methods=['GET', 'POST'])
def update_inventory(id):
    inventory_item = Inventory.query.get(id)

    if inventory_item:
        if request.method == 'POST':
            inventory_item.make = request.form['make']
            inventory_item.model = request.form['model']
            inventory_item.year = request.form['year']
            inventory_item.color = request.form['color']

            db.session.commit()


            flash(f'Inventory item {inventory_item.model} updated successfully!', 'success')
            return redirect(url_for('site.inventory'))

        return render_template('update_inventory.html', car=inventory_item, form = UpdateCar())

    else:
        flash(f'Inventory item with ID {id} not found!', 'error')
        return redirect(url_for('site.inventory'))


@site.route('/delete_inventory/<id>')
def delete_inventory(id):
    try:
        inventory_item = Inventory.query.get(id)

        if inventory_item:
            db.session.delete(inventory_item)
            db.session.commit()

            flash(f'Successfully deleted {inventory_item.model} from your inventory', 'delete-success')
        else:
            flash('Inventory item not found', 'delete-error')

    except Exception as e:
        flash(f'Error deleting inventory item: {str(e)}', 'delete-error')

    return redirect(url_for('site.inventory'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
<title>Car Inventory</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">miCar Inventory</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if 'home' in request.endpoint %}active{% endif %}">
              <a class="nav-link" href="{{ url_for('site.home') }}">Home <span class="sr-only">(current)</span></a>
            </li>
            {%  if current_user.is_authenticated %}
            <li class="nav-item {% if 'profile' in request.endpoint %}active{% endif %}">
              <a class="nav-link" href="{{  url_for('site.profile') }}">Profile</a>
            </li>
            <li class ="nav-item {% if 'inventory' in request.endpoint %}active{% endif %}">
              <a class="nav-link"  href="{{ url_for('site.inventory') }}">Inventory</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{  url_for('auth.logout') }}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item  {% if 'signin' in request.endpoint %}active{% endif %}">
              <a class="nav-link" href="{{  url_for('auth.signin') }}">Sign In</a>
            </li>
            <li class="nav-item {% if 'signup' in request.endpoint %}active{% endif %}">
              <a class="nav-link" href="{{  url_for('auth.signup') }}">Create Account</a>
            </li>
            {% endif %}
          </ul>
          </form>
        </div>
      </nav>
{%  block content %}
{%  endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class='form-control', placeholder='Enter your email') }}
        </fieldset>
    </div>

    <fieldset id="pass-field">
        {{ form.password.label }}
        {{ form.password(class='form-control', placeholder='Enter your password') }}
    </fieldset>

    {% if signup %}
        
        <fieldset id="first-name">
            {{ form.first_name.label }}
            {{ form.first_name(class='form-control', placeholder='First name here') }}
        </fieldset>

        <fieldset id="last-name">
            {{ form.last_name.label }}
            {{ form.last_name(class='form-control', placeholder='Last name here') }}
        </fieldset>
    {% endif %}

    <!-- Submit button area -->

        {{ form.submit_button(class='btn btn-primary btn-block mt-2') }}

</form>